--■■■■■■ 더미데이터 입력 ■■■■■--
-- 1 레벨 친구들
--
--제명유형	 
--제명유형 코드	제명사유
--EXP1	거래 사기
--EXP2	스토킹
--EXP3	아웃횟수초과

-- 1 제명 유형 
INSERT INTO EXPULSION_TYPE(EXPULSION_CODE,REASON)
VALUES ('EXP' || SEQ_EXP.NEXTVAL,'거래 사기');

INSERT INTO EXPULSION_TYPE(EXPULSION_CODE,REASON)
VALUES ('EXP' || SEQ_EXP.NEXTVAL,'스토킹');

INSERT INTO EXPULSION_TYPE(EXPULSION_CODE,REASON)
VALUES ('EXP' || SEQ_EXP.NEXTVAL,'아웃횟수초과');
--==>1 행 이(가) 삽입되었습니다.*3

-- 확인
SELECT *
FROM EXPULSION_TYPE;
/*
EXP1	거래 사기
EXP2	스토킹
EXP3	아웃횟수초과
*/
-- 2 탈퇴유형
INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'타 사이트의 유사 서비스 이용');

INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'속도가 느림');

INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'개인정보 변경으로 인한 재가입');

INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'자주 이용하지 않음');

INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'찾고자 하는 정보가 없음');

INSERT INTO LEAVE_TYPE(LEAVE_TYPE_CODE,REASON)
VALUES('LEAVE'||SEQ_LEAVE.NEXTVAL,'개인정보/사생활 침해 사례경험');

-- 확인
SELECT *
FROM LEAVE_TYPE;
/*
LEAVE1	타 사이트의 유사 서비스 이용
LEAVE2	개인정보/사생활 침해 사례경험
LEAVE3	속도가 느림
LEAVE4	개인정보 변경으로 인한 재가입
LEAVE5	자주 이용하지 않음
LEAVE6	찾고자 하는 정보가 없음
*/

-- 3 최소단위
INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'G');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'KG');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'개');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'근');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'oz');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'cm');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'m');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'in');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'yd');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'L');

INSERT INTO MINUNIT_TYPE(MINUNIT_TYPE_CODE,MINUNIT_TYPE)
VALUES('MINU'||SEQ_MINUNIT.NEXTVAL,'ml');



--확인
SELECT *
FROM MINUNIT_TYPE;
/*
MINU1	G
MINU2	KG
MINU3	개
MINU4	근
MINU5	oz
MINU6	cm
MINU7	m
MINU8	in
MINU9	yd
MINU10	L
MINU11	ml
*/

-- 커밋
COMMIT;

-- 4 광고 유형 

INSERT INTO ADV_TYPE (ADV_TYPE_CODE,ADV_LOC,ADV_COST)
VALUES('ADV_T'||SEQ_ADV_TYPE.NEXTVAL,'Top',80000);

INSERT INTO ADV_TYPE (ADV_TYPE_CODE,ADV_LOC,ADV_COST)
VALUES('ADV_T'||SEQ_ADV_TYPE.NEXTVAL,'Right',50000);

INSERT INTO ADV_TYPE (ADV_TYPE_CODE,ADV_LOC,ADV_COST)
VALUES('ADV_T'||SEQ_ADV_TYPE.NEXTVAL,'Bottom',30000);

-- 확인
SELECT *
FROM ADV_TYPE;
/*
ADV_T1	Top	80000
ADV_T2	Right	50000
ADV_T3	Bottom	30000
*/

-- 5 렌트 카테고리
SELECT *
FROM R_CATE;

INSERT INTO R_CATE(R_CATE_CODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL,'생활용품');
INSERT INTO R_CATE(R_CATE_CODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL,'스포츠');
INSERT INTO R_CATE(R_CATE_CODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL,'유아동/반려동물');
INSERT INTO R_CATE(R_CATE_CODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL,'디지털/가전/가구');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1','주방용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1','욕실용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1','침구류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1','문구류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','구기종목용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','등산용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','겨울스포츠용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','헬스/요가용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','자전거 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','수영용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','낚시/캠핑용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2','전동킥보드/전동휠');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3','잡화');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3','유아동용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3','기저귀/이유식');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3','강아지 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3','고양이 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4','모바일');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4','가전제품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4','음반/영상/관련기기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4','PC/모니터/주변기기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4','카메라/DSLR');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE5', '식기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE5', '냄비');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE5', '후라이팬');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE5', '칼');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '비누');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '면도기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '수건');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '샴푸/린스');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '치약');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '바디워시');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '휴지');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE6', '타올');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE7', '이불');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE7', '베개');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE7', '커튼');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '메모지');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '볼펜');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '연필');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '파우치');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '공책');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '스티커');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '공책');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE1', 'R_CATE8', '스티커');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '축구공');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '축구의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '야구공');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '야구배트');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '야구의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '농구공');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE9', '농구의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE10', '등산복');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE10', '기타 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE11', '스키/스노우보드');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE11', '스키 의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE12', '덤벨/바벨');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE12', '짐볼');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE12', '요가 매트');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE13', '자전거');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE13', '자전거헬멧');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE13', '보호대');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE14', '여성 수영복');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE14', '남성 수영복');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE14', '수영 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE14', '물놀이 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '캠핑 야외용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '캠핑 편의 용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '바다낚시장비');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '민물낚시장비');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '텐트/그늘막');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '낚시 장비');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE15', '캠핑 취사용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE16', '전동킥보드');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE2', 'R_CATE16', '전동휠');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE17', '신발');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE17', '모자');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE17', '가방');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE17', '액세서리');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE17', '양말');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '유모차');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '유아가구');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '보행기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '아기띠 ,');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '출산/임산부용품');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '이불/침구');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE18', '딸랑이/모빌');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE19', '기저귀');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE19', '이유식');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE20', '목줄');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE20', '사료');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE20', '간식');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE20', '의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE20', '장난감');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE21', '사료');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE21', '캣타워');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE21', '간식');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE21', '의류');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE3', 'R_CATE21', '장난감');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '스마트폰');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '케이스');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '보조배터리');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '보호필름');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '그립톡');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE22', '웨어러블(워치)');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '밥솥');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '다리미');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '냉장고');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '세탁기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', 'tv');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '고데기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '드라이기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE23', '청소기');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE24', '이어폰');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE24', '헤드폰');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE24', '스피커');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE25', '데스크탑');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE25', '노트북');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE25', '모니터');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE25', '키보드');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE25', '마우스');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', 'DSLR');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', '미러리스');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', '필름카메라');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', '렌즈');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', '삼각대');
INSERT INTO R_CATE(R_CATE_CODE,R_CATE_BCODE,R_CATE_MCODE,CATE_NAME)VALUES ( 'R_CATE'||SEQ_R_CATE.NEXTVAL, 'R_CATE4', 'R_CATE26', '카메라가방');

-- 1.5.1 공동구매 카테고리 유형

DELETE
FROM G_CATE;

DROP SEQUENCE SEQ_G_CATE;

CREATE SEQUENCE SEQ_G_CATE
NOCACHE;


INSERT INTO G_CATE(G_CATE_CODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL,'생활용품');
INSERT INTO G_CATE(G_CATE_CODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL,'스포츠');
INSERT INTO G_CATE(G_CATE_CODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL,'유아동/반려동물');
INSERT INTO G_CATE(G_CATE_CODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL,'디지털/가전/가구');
INSERT INTO G_CATE(G_CATE_CODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL,'식품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1','주방용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1','욕실용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1','침구류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1','문구류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','구기종목용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','등산용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','겨울스포츠용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','헬스/요가용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','자전거 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','수영용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','낚시/캠핑용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2','전동킥보드/전동휠');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3','잡화');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3','유아동용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3','기저귀/이유식');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3','강아지 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3','고양이 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4','모바일');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4','가전제품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4','음반/영상/관련기기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4','PC/모니터/주변기기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4','카메라/DSLR');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5','식품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5','건강식품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE6', '식기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE6', '냄비');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE6', '후라이팬');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE6', '칼');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '비누');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '면도기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '수건');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '샴푸/린스');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '치약');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '바디워시');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '휴지');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE7', '타올');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE8', '이불');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE8', '베개');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE8', '커튼');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '메모지');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '볼펜');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '연필');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '파우치');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '공책');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE1', 'G_CATE9', '스티커');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '축구공');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '축구의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '야구공');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '야구배트');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '야구의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '농구공');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE10', '농구의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE11', '등산복');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE11', '기타 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE12', '스키/스노우보드');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE12', '스키 의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE13', '덤벨/바벨');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE13', '짐볼');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE13', '요가 매트');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE14', '자전거');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE14', '자전거헬멧');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE14', '보호대');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE15', '여성 수영복');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE15', '남성 수영복');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE15', '수영 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE15', '물놀이 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '캠핑 야외용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '캠핑 편의 용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '바다낚시장비');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '민물낚시장비');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '텐트/그늘막');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '낚시 장비');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE16', '캠핑 취사용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE17', '전동킥보드');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE2', 'G_CATE17', '전동휠');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE18', '신발');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE18', '모자');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE18', '가방');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE18', '액세서리');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE18', '양말');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '유모차');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '유아가구');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '보행기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '아기띠 ,');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '출산/임산부용품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '이불/침구');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE19', '딸랑이/모빌');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE20', '기저귀');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE20', '이유식');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE21', '목줄');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE21', '사료');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE21', '간식');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE21', '의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE21', '장난감');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE22', '사료');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE22', '캣타워');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE22', '간식');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE22', '의류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE3', 'G_CATE22', '장난감');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '스마트폰');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '케이스');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '보조배터리');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '보호필름');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '그립톡');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE23', '웨어러블(워치)');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '밥솥');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '다리미');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '냉장고');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '세탁기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', 'tv');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '고데기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '드라이기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE24', '청소기');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE25', '이어폰');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE25', '헤드폰');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE25', '스피커');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE26', '데스크탑');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE26', '노트북');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE26', '모니터');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE26', '키보드');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE26', '마우스');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', 'DSLR');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', '미러리스');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', '필름카메라');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', '렌즈');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', '삼각대');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE4', 'G_CATE27', '카메라가방');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '계란');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '커피');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '견과류');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '과일');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '채소');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '음료');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '과자');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '가공식품');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE28', '쌀');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE29', '홍삼');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE29', '프로틴');
INSERT INTO G_CATE(G_CATE_CODE,G_CATE_BCODE,G_CATE_MCODE,CATE_NAME)VALUES ( 'G_CATE'||SEQ_G_CATE.NEXTVAL, 'G_CATE5', 'G_CATE29', '비타민');

SELECT *
FROM G_CATE;
/*
G_CATE1			생활용품
G_CATE2			스포츠
G_CATE3			유아동/반려동물
G_CATE4			디지털/가전/가구
G_CATE5			식품
*/


-- 6 영구제명회원   ======================================================================================
SELECT *
FROM B_USER;


INSERT INTO PERMANENT_EXPULSION(PERMANENT_EXPULSION_CODE,B_USER_CODE,EXPULSION_CODE)
VALUES ('EXP_U'||SEQ_EXP_U.NEXTVAL,'USER8','EXP1');


-- 확인
SELECT *
FROM PERMANENT_EXPULSION;
/*
EXP_U1	USER8	EXP1	20/07/09
*/

COMMIT;

-- 7 관심 공동구매 키워드 입력   ===================================================================

-- 유저9 생활용품,스포츠 관심
INSERT INTO G_CATE_INPUT(G_CATE_INPUT_CODE,G_CATE_CODE,B_USER_CODE)
VALUES('LIKE_G'||SEQ_LIKE_G.NEXTVAL,'G_CATE1','USER9');
INSERT INTO G_CATE_INPUT(G_CATE_INPUT_CODE,G_CATE_CODE,B_USER_CODE)
VALUES('LIKE_G'||SEQ_LIKE_G.NEXTVAL,'G_CATE2','USER9');

-- 유저 10 생활용품,유아동/반려동물 관심
INSERT INTO G_CATE_INPUT(G_CATE_INPUT_CODE,G_CATE_CODE,B_USER_CODE)
VALUES('LIKE_G'||SEQ_LIKE_G.NEXTVAL,'G_CATE1','USER10');
INSERT INTO G_CATE_INPUT(G_CATE_INPUT_CODE,G_CATE_CODE,B_USER_CODE)
VALUES('LIKE_G'||SEQ_LIKE_G.NEXTVAL,'G_CATE3','USER10');


-- 확인
SELECT *
FROM G_CATE_INPUT;
/*
LIKE_G1	G_CATE1	USER9
LIKE_G2	G_CATE2	USER9
LIKE_G3	G_CATE1	USER10
LIKE_G4	G_CATE3	USER10
*/
--======================================================================================================================================

-- 8 CONNECTION 최근 접속 일자 

INSERT INTO CONNECTION(CONNECTION_CODE,B_USER_CODE)
VALUES('COND'||SEQ_CONDATE.NEXTVAL,'USER9');

INSERT INTO CONNECTION(CONNECTION_CODE,B_USER_CODE)
VALUES('COND'||SEQ_CONDATE.NEXTVAL,'USER10');

-- 9 바나나 점수 내역 

INSERT INTO BANANA_SCORE(BANANA_SCORE_CODE,B_USER_CODE,BANANA_SCORE)
VALUES('BANA'|| SEQ_BANANA.NEXTVAL,'USER9',10);

INSERT INTO BANANA_SCORE(BANANA_SCORE_CODE,B_USER_CODE,BANANA_SCORE)
VALUES('BANA'|| SEQ_BANANA.NEXTVAL,'USER10',10);

COMMIT;


--===========================================================================================================================================
-- 10.지역 카테고리 추가
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'서울특별시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'부산광역시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'대구광역시 ');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'인천광역시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'광주광역시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'대전광역시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'울산광역시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'세종특별자치시');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'경기도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'강원도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'충청북도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'충청남도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'전라북도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'전라남도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'경상북도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'경상남도');
INSERT INTO LOC(LOC_CODE, LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL,'제주특별자치도');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '종로구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '용산구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '성동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '광진구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '동대문구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '중랑구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '성북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '강북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '도봉구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '노원구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '은평구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '서대문구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '마포구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '양천구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '강서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '구로구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '금천구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '영등포구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '동작구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '관악구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '서초구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '강남구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '송파구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC1', '강동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '영도구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '부산진');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '동래구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '남구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '해운대구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '사하구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '금정구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '강서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '연제구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '수영구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '사상구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC2', '기장군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '남구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '수성구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '달서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC3', '달성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '미추홀구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '연수구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '남동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '부평구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '계양구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '강화군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC4', '옹진군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC5', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC5', '서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC5', '남구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC5', '북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC5', '광산구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC6', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC6', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC6', '서구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC6', '유성구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC6', '대덕구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC7', '중구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC7', '남구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC7', '동구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC7', '북구');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC7', '울주군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC8', '세종특별자치시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '수원시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '성남시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '고양시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '용인시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '부천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '안산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '안양시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '남양주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '화성시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '평택시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '의정부시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '시흥시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '파주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '광명시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '김포시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '군포시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '광주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '이천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '양주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '오산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '구리시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '안성시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '포천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '의왕시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '하남시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '여주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '양평군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '동두천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '과천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '가평군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC9', '연천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '춘천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '원주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '강릉시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '동해시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '태백시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '속초시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '삼척시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '홍천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '횡성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '영월군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '평창군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '정선군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '철원군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '화천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '양구군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '인제군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '고성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC10', '양양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '청주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '충주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '제천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '보은군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '옥천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '영동군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '진천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '괴산군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '음성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '단양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC11', '증평군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '천안시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '공주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '보령시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '아산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '서산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '논산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '계룡시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '당진시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '금산군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '부여군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '서천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '청양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '홍성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '예산군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC12', '태안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '전주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '군산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '익산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '정읍시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '남원시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '김제시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '완주군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '진안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '무주군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '장수군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '임실군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '순창군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '고창군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC13', '부안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '목포시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '여수시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '순천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '나주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '광양시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '담양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '곡성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '구례군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '고흥군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '보성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '화순군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '장흥군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '강진군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '해남군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '영암군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '무안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '함평군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '영광군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '장성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '완도군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '진도군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC14', '신안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '포항시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '경주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '김천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '안동시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '구미시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '영주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '영천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '상주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '문경시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '경산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '군위군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '의성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '청송군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '영양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '영덕군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '청도군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '고령군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '성주군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '칠곡군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '예천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '봉화군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '울진군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC15', '울릉군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '창원시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '진주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '통영시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '사천시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '김해시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '밀양시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '거제시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '양산시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '의령군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '함안군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '창녕군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '고성군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '남해군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '하동군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '산청군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '함양군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '거창군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC16', '합천군');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC17', '제주시');
INSERT INTO LOC(LOC_CODE,LOC_BCODE,LOC_NAME) VALUES( 'LOC'||SEQ_LOC.NEXTVAL, 'LOC17', '서귀포시');


--===========================================================================================================================
SELECT *
FROM ALARM_HEAD_TYPE;

--○ 알림 머리글 유형 더미 데이터 입력
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'공통');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'포인트');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'리뷰');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'바나나점수');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'신고');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'팔로워');
INSERT INTO ALARM_HEAD_TYPE(ALARM_HEAD_TYPE_CODE,ALARM_HEAD_TYPE)
VALUES('AR_H'||SEQ_ALARM_H.NEXTVAL,'기타');

--===========================================================================================================================
SELECT *
FROM ALARM_CONTENT_TYPE;
--○ 알림 내용 유형 INSERT
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H6','결제가 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H6','한불 처리 되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H6','출금이 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H7','리뷰를 작성해주세요.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H8','바나나 점수가 적립되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H9','신고 접수가 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H9','신고 처리가 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H9','회원님에 대한 신고가 접수되었습니다.이의제기 신청을 해주세요');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H10','회원님을 팔로우하는 팔로워가 생겼습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','등록이 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','신청이 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','성사가 완료되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','결석 처리가 되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','결석자가 있습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','회원님의 게시물에 댓글이 달렸습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H1','만남 하루 전 입니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H1','반납이 완료 되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H1','장소와 시간이 재입력되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H1','장소와 시간을 재입력해주세요.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H5','신청이 취소되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H2','만남 하루 전 입니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H2','반납이 완료 되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H2','장소와 시간이 재입력되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H2','장소와 시간을 재입력해주세요.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H2','제공 게시물이 등록되었습니다.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H3','중간점검 여부를 확인해주세요.');
INSERT INTO ALARM_CONTENT_TYPE(ALARM_CONTENT_TYPE_CODE,ALARM_HEAD_TYPE_CODE,ALARM_CONTENT_TYPE)
VALUES('AR_C'||SEQ_ALARM.NEXTVAL,'AR_H3','수량을 재입력 해주세요.');

commit;
--===========================================================================================================================
--○ 게시물/댓글 신고 처리 유형
SELECT *
FROM PNR_REPORT_PROC_TYPE;


--○게시물/댓글 신고 처리 유형 INSERT
INSERT INTO PNR_REPORT_PROC_TYPE(PNR_REPORT_PROC_TYPE_CODE,PNR_REPORT_PROC_STATE)
VALUES('PNRP'||SEQ_PNR_R_P_T.NEXTVAL,0);
INSERT INTO PNR_REPORT_PROC_TYPE(PNR_REPORT_PROC_TYPE_CODE,PNR_REPORT_PROC_STATE)
VALUES('PNRP'||SEQ_PNR_R_P_T.NEXTVAL,0);

--===========================================================================================================================

--○ 관리자 등록 INSERT
INSERT INTO ADMIN(ADMIN_CODE,ID,PW,NAME)
VALUES('ADMIN'||SEQ_ADMIN.NEXTVAL,'easthui','java006$','김동휘');
INSERT INTO ADMIN(ADMIN_CODE,ID,PW,NAME)
VALUES('ADMIN'||SEQ_ADMIN.NEXTVAL,'dawngusul','java006$','임효림');
INSERT INTO ADMIN(ADMIN_CODE,ID,PW,NAME)
VALUES('ADMIN'||SEQ_ADMIN.NEXTVAL,'straight0','java006$','전진영');
INSERT INTO ADMIN(ADMIN_CODE,ID,PW,NAME)
VALUES('ADMIN'||SEQ_ADMIN.NEXTVAL,'lightfe','java006$','최철녕');

--○관리자 등록 테이블 조회
SELECT *
FROM ADMIN;


--===========================================================================================================================












