-- ■■■■■ 자율협력구매 프로시저 ■■■■■■-

-- 자율협력구매 리뷰 등록 프로시저
-- 1. 신뢰도 점수 내역 insert
-- 2. 바나나 점수 내역 insert
-- 3. 공통협구매 리뷰 등록

CREATE OR REPLACE PROCEDURE PRC_J_REVIEW
(

V_CREDIT_SCORE 		    IN 	CREDIT_SCORE.CREDIT_SCORE%TYPE	--신뢰도점수
,V_B_USER_CODE		    IN        B_USER.B_USER_CODE%TYPE -- 유저코드
,V_J_SUCCESS_CODE       IN      J_SUCCESS.J_SUCCESS_CODE%TYPE -- 공통협력구매 성사 코드
,V_CONTENT			    IN      J_REVIEW.CONTENT%TYPE -- 리뷰내용
)
IS
	-- 변수 선언
V_CREDIT_SCORE_CODE		CREDIT_SCORE.CREDIT_SCORE_CODE%TYPE := 'BRIX' || SEQ_BRIX.NEXTVAL;-- CS1
V_BANANA_SCORE_CODE 	BANANA_SCORE.BANANA_SCORE_CODE%TYPE := 'BANA' || SEQ_BANANA.NEXTVAL;--BS1

BEGIN
	-- 실행문
	-- 1. 신뢰도 점수 내역 INSERT
	INSERT INTO CREDIT_SCORE ( CREDIT_SCORE_CODE,CREDIT_SCORE,B_USER_CODE)
    VALUES (V_CREDIT_SCORE_CODE,V_CREDIT_SCORE ,V_B_USER_CODE);

    --2. 바나나점수 내역 INSERT
	INSERT INTO BANANA_SCORE(BANANA_SCORE_CODE, B_USER_CODE, BANANA_SCORE)
	VALUES (V_BANANA_SCORE_CODE, V_B_USER_CODE, 20);

	--3. 자율협력구매 리뷰 등록 INSERT
	INSERT INTO J_REVIEW(J_REVIEW_CODE,J_SUCCESS_CODE,SCORE,CONTENT,CREDIT_SCORE_CODE)
	VALUES( 'J_REV' || SEQ_J_REVIEW.NEXTVAL,V_J_SUCCESS_CODE ,V_CREDIT_SCORE ,V_CONTENT,V_CREDIT_SCORE_CODE);


	--4. 커밋
	--COMMIT;
END;


-- 9. 자율협력구매 게시물 신고 처리
-- 1) 경고내역등록 INSERT 
-- 2) 자율협력구매 게시물 신고 처리 INSERT

CREATE OR REPLACE PROCEDURE PRC_J_POST_REPORT_PRC
(
 V_B_USER_CODE             IN     B_USER.B_USER_CODE%TYPE    -- 유저코드
,V_J_POST_REPORT_CODE     IN  J_POST_REPORT.J_POST_REPORT_CODE%TYPE-- 자율협력구매 게시물 신고 코드
,V_ADMIN_CODE             IN          ADMIN.ADMIN_CODE%TYPE-- 관리자 등록 코드
,V_PNR_REPORT_PROC_TYPE_CODE     IN    PNR_REPORT_PROC_TYPE.PNR_REPORT_PROC_TYPE_CODE%TYPE--게시물/댓글 신고처리 유형 코드
)
IS

V_WARNING_CODE      WARNING.WARNING_CODE%TYPE := 'WAR' || SEQ_WAR.NEXTVAL;  -- WAR1

BEGIN

    -- 1) 경고내역 등록 INSERT
     INSERT INTO WARNING (WARNIN_CODE, B_USER_CODE)
     VALUES (V_WARNING_CODE,V_B_USER_CODE);
     
     -- 2) 자율협력구매 게시물 신고 처리 INSERT
     INSERT INTO J_POST_REPORT_PROC(J_POST_REPORT_PROC_CODE, J_POST_REPORT_CODE, ADMIN_CODE, PNR_REPORT_PROC_TYPE_CODE, WARNING_CODE)
     VALUES('J_PRP'|| SEQ_J_POST_REP_PRC.NEXTVAL, V_J_POST_REPORT_CODE, V_ADMIN_CODE, V_PNR_REPORT_PROC_TYPE_CODE, V_WARNING_CODE);


    -- 3) 커밋
    -- COMMIT;

END;
--===================================================================================================================================

-- 13. 자율협력구매 거래 신고 처리 프로시저(유효한 신고일때)
-- 신고자 
-- 1.포인트 내역 등록 insert 2. 자율협력구매 거래 신고처리 insert    
-- 신고 대상자
-- 1.포인트 내역 등록 insert 2.아웃 내역 등록 insert 3. 자율협력구매 거래 신고처리 insert

CREATE OR REPLACE PROCEDURE PRC_J_DEAL_REPORT_PROC
(
  V_B_USER_CODE             IN     B_USER.B_USER_CODE%TYPE   -- 신고자유저코드
, V_B_USER_REP_CODE             IN     B_USER.B_USER_CODE%TYPE   -- 신고당한사람유저코드
, V_POINT                    IN     POINT_LIST.POINT%TYPE  -- 입력받을 포인트
, V_J_DEAL_REPORT_CODE      IN      J_DEAL_REPORT.J_DEAL_REPORT_CODE%TYPE -- 자율협력구매 거래 신고 코드
, V_ADMIN_CODE             IN          ADMIN.ADMIN_CODE%TYPE-- 관리자 등록 코드
, V_DEAL_REPORT_PROC_TYPE_CODE  IN     DEAL_REPORT_PROC_TYPE.DEAL_REPORT_PROC_TYPE_CODE%TYPE    -- 신고자에 대한 거래 신고처리 유형 코드
, V_DEAL_REPORT_PROC_TYPE_CODE2  IN     DEAL_REPORT_PROC_TYPE.DEAL_REPORT_PROC_TYPE_CODE%TYPE    -- 신고대상자에 대한 거래 신고처리 유형 코드
, V_ANSWER                      IN      J_DEAL_REPORT_PROC.ANSWER%TYPE  -- 신고답변

)
IS
 V_POINT_LIST_CODE     POINT_LIST.POINT_LIST_CODE%TYPE := 'POLIS'||SEQ_POINT_LIST.NEXTVAL;  -- 신고자 포인트 내역 등록코드
 V_REP_POINT_LIST_CODE     POINT_LIST.POINT_LIST_CODE%TYPE := 'POLIS'||SEQ_POINT_LIST.NEXTVAL;  -- 신고자대상자 포인트 내역 등록코드
 V_OUT_CODE            OUT.OUT_CODE%TYPE := 'OUT' ||SEQ_OUT.NEXTVAL;

BEGIN

    -- 1) 포인트 내역 등록 INSERT  -- 신고자 돈 환불 (+)
    -- SDATE,STATE는 기본값으로
    INSERT INTO POINT_LIST(POINT_LIST_CODE, B_USER_CODE, POINT)
    VALUES(V_POINT_LIST_CODE,V_B_USER_CODE, V_POINT );
    
    -- 2) 포인트 내역 등록 INSERT  -- 신고대상자 돈 회수 (-)
    -- SDATE,STATE는 기본값으로
    INSERT INTO POINT_LIST(POINT_LIST_CODE, B_USER_CODE, POINT)
    VALUES(V_REP_POINT_LIST_CODE, V_B_USER_REP_CODE,-V_POINT );
    
    -- 3) 아웃 내역 등록 INSERT(신고 대상자)
    INSERT INTO OUT(OUT_CODE,B_USER_CODE)
    VALUES(V_OUT_CODE, V_B_USER_REP_CODE)
    
    -- 4) 신고자 신고 처리 INSERT  -- 환불시간 처리 시간 디폴트
    INSERT INTO J_DEAL_REPORT_PROC(J_DEAL_REPORT_PROC_CODE, J_DEAL_REPORT_CODE, ADMIN_CODE, DEAL_REPORT_PROC_TYPE_CODE, ANSWER,POINT_LIST_CODE)
    VALUES('J_DRP' || SEQ_J_D_REP_PRC.NEXTVAL,V_J_DEAL_REPORT_CODE,V_ADMIN_CODE, V_DEAL_REPORT_PROC_TYPE_CODE, V_ANSWER, V_POINT_LIST_CODE);
    
    -- 5) 신고자대상자 신고 처리 INSERT  -- 환불시간 처리 시간 디폴트
    INSERT INTO _DEAL_REPORT_PROC(J_DEAL_REPORT_PROC_CODE, J_DEAL_REPORT_CODE, ADMIN_CODE, DEAL_REPORT_PROC_TYPE_CODE, ANSWER,POINT_LIST_CODE, OUT_CODE)
    VALUES('J_DRP' || SEQ_J_D_REP_PRC.NEXTVAL,V_J_DEAL_REPORT_CODE,V_ADMIN_CODE, V_DEAL_REPORT_PROC_TYPE_CODE2, V_ANSWER, V_REP_POINT_LIST_CODE,V_OUT_CODE)
    
    -- 6) 커밋
    -- COMMIT;
    
END;
--===================================================================================================================================

-- ○ 자율협력 구매 신청 시 프로시저
-- 1. 포인트 내역 등록 INSERT
-- 2. 자율협력구매 신청 INSERT
CREATE OR REPLACE PROCEDURE PRC_G_APPLY
(
 V_B_USER_CODE          IN B_USER.B_USER_CODE%TYPE -- 유저코드
, V_POINT               IN POINT_LIST.POINT%TYPE   -- 포인트
, V_J_POST_CODE         IN J_POST.J_POST_CODE%TYPE -- 자율협력구매 게시물 등록 코드
, V_AMOUNT              IN J_APPLY.AMOUNT%TYPE     -- 주문 수량
)
IS
V_POINT_LIST_CODE   POINT_LIST.POINT_LIST_CODE%TYPE := 'POLIS' || SEQ_POINT.NEXTVAL;-- PL1

BEGIN
-- 실행문
-- 1. 포인트 내역 등록 INSERT
INSERT INTO POINT_LIST(POINT_LIST_CODE, B_USER_CODE, POINT)
VALUES(V_POINT_LIST_CODE, V_B_USER_CODE, V_POINT);

-- 2. 자율협력구매 신청 INSERT
INSERT INTO J_APPLY(J_APPLY_CODE, J_POST_CODE, B_USER_CODE, AMOUNT,POINT_LIST_CODE)
VALUES('J_APPLY'||SEQ_J_APPLY.NEXTVAL, V_J_POST_CODE, V_B_USER_CODE, V_AMOUNT, V_POINT_LIST_CODE);

-- 3. 커밋
-- COMMIT;
END;


--==============================================================================================================
-- ○ 주문 수량 재입력
--1.포인트 내역 등록 2.재입력 insert 
CREATE OR REPLACE PROCEDURE PRC_J_REAPPLY
(
 V_B_USER_CODE          IN B_USER.B_USER_CODE%TYPE -- 유저코드
,V_POINT                IN POINT_LIST.POINT%TYPE
,V_J_COST_DROP_CODE     IN J_COST_DROP.J_COST_DROP_CODE%TYPE
, V_RE_AMOUNT             IN J_REAPPLY.RE_AMOUNT%TYPE
)
IS

    V_POINT_LIST_CODE   POINT_LIST.POINT_LIST_CODE%TYPE :='POLIS'|| SEQ_POINT_LIST.NEXTVAL;

BEGIN

    -- 1. 포인트 내역 등록
    INSERT INTO POINT_LIST(POINT_LIST_CODE, B_USER_CODE, POINT)
    VALUES(V_POINT_LIST_CODE, V_B_USER_CODE,V_POINT );
    
    -- 2. 주문 재입력 INSERT
    INSERT INTO J_REAPPLY(J_REAPPLY_CODE, J_COST_DROP_CODE, B_USER_CODE, POINT_LIST_CODE, RE_AMOUNT)
    VALUES('J_REAP'||SEQ_J_REAPPLY.NEXTVAL,V_J_COST_DROP_CODE, V_B_USER_CODE, V_POINT_LIST_CODE,V_RE_AMOUNT );
    
    
    -- 커밋
    --COMMIT;

END;
