--○ 공통협력 구매 거래 등록 INSERT 
INSERT INTO G_POST(G_POST_CODE,B_USER_CODE,G_CATE_CODE,LOC_CODE,TITLE,CONTENT,VIEWS,BRAND,START_DATE,END_DATE,COST,DIS_COST,MEMBER_NUM,BUN_LOC,BUN_DATE,RETURN_DATE,RECEIPT_DATE)
VALUES('G_POST'||SEQ_G_POST.NEXTVAL,'USER14','G_CATE142','LOC95','홍삼 같이 사서 나눠가져요~','지치고 힘들 때 홍삼 먹으면 힘나요!같이 구매해요~',33,'정관장',TO_DATE('2020-07-15 13:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-25 13:00:00','YYYY-MM-DD HH24:MI:SS'),25000,20000,5,'LOC95',TO_DATE('2020-07-30 13:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2020-07-31 18:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-29 13:00:00','YYYY-MM-DD HH24:MI:SS'));
            
            
--○ 공통협력 구매 사진 등록
INSERT INTO G_PHOTO(G_PHOTO_CODE,G_POST_CODE,PHOTO)
VALUES('G_PHOTO'||SEQ_G_PHOTO.NEXTVAL,'G_POST1','홍삼사진.jpg');

--○ 공통협력 구매 거래 등록 INSERT 
INSERT INTO G_POST(G_POST_CODE,B_USER_CODE,G_CATE_CODE,LOC_CODE,TITLE,CONTENT,VIEWS,BRAND,START_DATE,END_DATE,COST,DIS_COST,MEMBER_NUM,BUN_LOC,BUN_DATE,RETURN_DATE,RECEIPT_DATE)
VALUES('G_POST'||SEQ_G_POST.NEXTVAL,'USER15','G_CATE40','LOC129','휴지 필요하신 분~','휴지 필요하신가요?전 휴지 많아요:)',23,'크리넥스',TO_DATE('2020-07-10 08:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-14 12:50:00','YYYY-MM-DD HH24:MI:SS'),20000,15000,3,'LOC129',TO_DATE('2020-07-16 13:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2020-07-17 18:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-15 13:00:00','YYYY-MM-DD HH24:MI:SS'));
            
--○ 공통협력 구매 사진 등록
INSERT INTO G_PHOTO(G_PHOTO_CODE,G_POST_CODE,PHOTO)
VALUES('G_PHOTO'||SEQ_G_PHOTO.NEXTVAL,'G_POST3','휴지자랑.jpg');


--○ 댓글 작성
INSERT INTO G_REPLY(G_REPLY_CODE,G_POST_CODE,B_USER_CODE,REPLY,L_LEVEL)
VALUES('G_REP'||SEQ_G_REPLY.NEXTVAL,'G_POST3','USER16','누가 이렇게 자랑 게시물을 쓰나요!신고합니다.',0);
--신고 당할 댓글 작성
INSERT INTO G_REPLY(G_REPLY_CODE,G_POST_CODE,B_USER_CODE,G_REPLY_REF_CODE,REPLY,L_LEVEL)
VALUES('G_REP'||SEQ_G_REPLY.NEXTVAL,'G_POST3','USER15','G_REP1','메롱이다',1);

--○ 댓글 신고 (USER16이 USER15를 신고.)
INSERT INTO G_REPLY_REPORT(G_REPLY_REPORT_CODE,G_REPLY_CODE,REPLY_REPORT_TYPE_CODE,B_USER_CODE)
VALUES('G_REPR'||SEQ_G_REPLY_REP.NEXTVAL,'G_REP2','REPRT5','USER16');

--○게시물 신고(USER15게시물 신고 당하기,USER16이 게시물 신고)
INSERT INTO G_POST_REPORT(G_POST_REPORT_CODE,POST_REPORT_TYPE_CODE,B_USER_CODE,G_POST_CODE)
VALUES('G_PR'||SEQ_G_POST_REP.NEXTVAL,'POSRT5','USER16','G_POST3');

--○ 거래 신고 당할 공통협력 구매 거래 등록 추가 INSERT 
INSERT INTO G_POST(G_POST_CODE,B_USER_CODE,G_CATE_CODE,LOC_CODE,TITLE,CONTENT,VIEWS,BRAND,START_DATE,END_DATE,COST,DIS_COST,MEMBER_NUM,BUN_LOC,BUN_DATE,RETURN_DATE,RECEIPT_DATE)
VALUES('G_POST'||SEQ_G_POST.NEXTVAL,'USER9','G_CATE46','LOC115','볼펜 같이 사서 나눠가져요~','볼펜 한 묶음 사서 같이 나눠 가질 사람~',4,'모나미',TO_DATE('2020-07-09 13:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-12 13:00:00','YYYY-MM-DD HH24:MI:SS'),20000,12000,4,'LOC115',TO_DATE('2020-07-14 15:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2020-07-16 18:00:00','YYYY-MM-DD HH24:MI:SS')
            ,TO_DATE('2020-07-13 13:00:00','YYYY-MM-DD HH24:MI:SS'));
            
            
--○ 추가된 거래 공통협력 구매 사진 등록
INSERT INTO G_PHOTO(G_PHOTO_CODE,G_POST_CODE,PHOTO)
VALUES('G_PHOTO'||SEQ_G_PHOTO.NEXTVAL,'G_POST4','볼펜사진.jpg');


--○ 공통협력 구매 거래 신고하기(USER10 이 USER9에게 )
INSERT INTO G_DEAL_REPORT(G_DEAL_REPORT_CODE,G_SUCCESS_CODE,G_DEAL_REPORT_TYPE_CODE,F_FILE,CONTENT,DEAL_REPORTER_TYPE_CODE)
VALUES('G_DRP'||SEQ_G_D_REP.NEXTVAL,'G_SUCCESS2','GDERT3','모나미가 아님.jpg','올리셨던 사진이랑 볼펜 종류가 달라요~!!','DREPO4');


 -- 공통협력 상품 반환 INSERT     
 
INSERT INTO(
   SELECT I.G_RETURN_ITEM_CODE, I.G_DEAL_REPORT_PROC_CODE,I.POINT_LIST_CODE,I.REFUND_DATE
   FROM G_APPLY A LEFT JOIN G_POST P
   ON A.G_POST_CODE = P.G_POST_CODE 
               LEFT JOIN G_SUCCESS S
               ON P.G_POST_CODE = S.G_POST_CODE
               LEFT JOIN G_DEAL_REPORT D 
               ON D.G_SUCCESS_CODE = S.G_SUCCESS_CODE
               LEFT JOIN G_DEAL_REPORT_PROC R
               ON R.G_DEAL_REPORT_CODE = D.G_DEAL_REPORT_CODE
               RIGHT JOIN G_RETURN_ITEM I
               ON R.G_DEAL_REPORT_PROC_CODE= I.G_DEAL_REPORT_PROC_CODE
              WHERE A.B_USER_CODE = V_B_USER_CODE)
VALUES('G_RETI'||SEQ_G_RETURN_ITEM.NEXTVAL, V_G_DEAL_REPORT_PROC_CODE, V_POINT_LIST_CODE, V_REFUND_DATE);










































