DESC G_POST;

SELECT *
FROM G_CATE;

-- 중분류 카테 찾기
SELECT G_CATE_CODE AS gCateCode, CATE_NAME AS cateName
FROM G_CATE
WHERE G_CATE_BCODE = 'G_CATE1' AND G_CATE_MCODE IS NULL ;


-- b코드가 대분류 코드거나 m 코드가 널인 친구가 중분류

-- 소분류 카테 찾기
SELECT G_CATE_MCODE AS gCateMcode, CATE_NAME AS cateName
FROM G_CATE
WHERE G_CATE_BCODE = 'G_CATE1' AND G_CATE_MCODE = 'G_CATE6' ;
-- 대분류 , 중분류

-- b 코드가 대분류 코드거나 m 코드가 중분류인 친구 


SELECT TITLE, START_DATE, END_DATE, BUN_LOC
	FROM G_APPLY A LEFT JOIN G_POST P
	ON A.G_POST_CODE = P.G_POST_CODE;

SELECT TITLE, START_DATE, END_DATE, BUN_LOC
FROM G_APPLY A LEFT JOIN G_POST P
ON A.G_POST_CODE = P.G_POST_CODE;


WHERE A.B_USER_CODE = 'USER39';

SELECT *
FROM R_REPLY;


-- 내가 쓴 댓글 VIEW

CREATE OR REPLACE VIEW VIEW_USER_REPLY_LIST
AS
SELECT RP.TITLE AS TITLE, RR.WDATE AS WDATE, REPLY AS REPLY, RR.B_USER_CODE, RR.R_REPLY_CODE AS REPLY_CODE
        ,(
            SELECT COUNT(*)
            FROM R_REPLY_LIKE RK 
            WHERE R_REPLY_CODE = RR.R_REPLY_CODE
        )AS REPLY_LIKE
FROM R_REPLY RR LEFT JOIN R_POST RP
ON RP.R_POST_CODE = RR.R_POST_CODE
UNION
SELECT GP.TITLE AS TITLE, GR.WDATE AS WDATE, REPLY AS REPLY, GR.B_USER_CODE, GR.G_REPLY_CODE AS REPLY_CODE
        ,(
            SELECT COUNT(*)
            FROM G_REPLY_LIKE GK 
            WHERE G_REPLY_CODE = GR.G_REPLY_CODE
        )AS REPLY_LIKE
FROM G_REPLY GR LEFT JOIN G_POST GP
ON GP.G_POST_CODE = GR.G_POST_CODE;



-- 뷰 확인
SELECT TITLE, WDATE, REPLY, B_USER_CODE, REPLY_LIKE, REPLY_CODE
FROM VIEW_USER_REPLY_LIST
WHERE B_USER_CODE ='USER49'
ORDER BY WDATE ASC;

EXEC PRC_G_REPLY('G_POST27','USER49','계란 싱싱한가요?',NULL,0, '' );

-- 렌트 댓글 수정
UPDATE R_REPLY
SET REPLY ='누가 드라이기를 대여해서 쓰나요?ㅋㅅㅋ'
WHERE R_REPLY_CODE ='R_REP9';



-- 공동구매 댓글 수정
UPDATE R_REPLY
SET REPLY ='삭제된 댓글입니다.'
WHERE R_REPLY_CODE ='R_REP9';



SELECT *
FROM G_REPLY;
/*
G_POST22	G_REP8		USER38	20/07/08	볼펜 제가 파는데 엄청 좋아요!한번 써보실래요?저희 가게 이름은 바나나문구입니다.놀러오세요	0
G_POST22	G_REP9		USER39	20/07/09	모나미 좋죠!저 살래요!	0
G_POST22	G_REP10	G_REP8	USER40	20/07/09	여기서 이렇게 홍보하지 마세요	1
G_POST27	G_REP11		USER49	20/07/20	계란 싱싱한가요?	0
*/


COMMIT;

SELECT *
FROM R_REPLY;

SELECT *
FROM CHUL_CHECK;

SELECT *
FROM R_REVIEW;
/*
R_REP9	R_POST12		USER49	20/08/01	누가 드라이기를 대여해서 쓰나요?ㅋㅅㅋ	0
R_REP10	R_POST12	R_REP9	USER50	20/08/01	네?	1
*/

-- 마이 바나나 /활동 점수 
SELECT BS.BANANA_SCORE_CODE AS BANANA_SCORE_CODE, J.B_USER_CODE AS B_USER_CODE, BS.BANANA_SCORE AS BANANA_SCORE, J.NICKNAME AS NICKNAME
FROM BANANA_SCORE BS LEFT JOIN JOIN J
ON BS.B_USER_CODE = J.B_USER_CODE
WHERE BS.B_USER_CODE ='USER48';


SELECT *
FROM CREDIT_SCORE;

-- 조인 테이블
SELECT *
FROM R_REVIEW RR LEFT JOIN CREDIT_SCORE CS
ON RR.CREDIT_SCORE_CODE = CS.CREDIT_SCORE_CODE
                    LEFT JOIN ;
