-- ■■■■■  자율 협력 더미 데이터 넣기 ■■■■■



-- 소상공인 신청 INSERT 문 -- 카테고리는 대분류로 받는다.
INSERT INTO SOSANG_APPLY(SOSANG_APPLY_CODE, G_CATE_CODE, B_USER_CODE, BUSINESS_NAME, BUSINESS_ADDR, BANK_COPY, BUSINESS_NUM, BUSINESS_IDENTITY)
VALUES('SOSA'|| SEQ_SOSANG.NEXTVAL, 'G_CATE1', 'USER17','수진이네', '서울특별시 영등포구 문래동4가 수진빌딩', 'BANK_COPY.jpg', '100-01-12342','BUSINESS_IDENTITY.jpg');

        
-- 소상공인 수락 INSERT 문
INSERT INTO SOSANG_APPLY_ACCEPT(SOSANG_APPLY_ACCEPT_CODE, SOSANG_APPLY_CODE, ADMIN_CODE)
VALUES('SOSA_AC'||SEQ_SOSANG_ACC.NEXTVAL, 'SOSA3' , 'ADMIN1' );


-- 자율협력구매 게시물 등록
INSERT INTO J_POST(J_POST_CODE, B_USER_CODE, G_CATE_CODE, LOC_CODE, TITLE, CONTENT
                    , START_DATE, END_DATE, COST, DIS_COST, GOAL, MINUNIT_TYPE_CODE
                    , BUN_LOC, BUN_DATE, RETURN_DATE)
VALUES('J_POST'||SEQ_J_POST.NEXTVAL, 'USER17','G_CATE30','LOC36','접시 100장 모이면 싸게 드려요'
        ,'망했어요..! 접시가 원래 10장에 3만원인데
          묻지도 따지지도 않는 독일제 접시 입니다..
          100장이 모이면 단돈 특.별.가! 10장에![1.만.원]에
          모시고 있습니다.', TO_DATE('2020-07-14 18:00:00','YYYY-MM-DD HH24:MI:SS')
        , TO_DATE('2020-07-21 18:00:00','YYYY-MM-DD HH24:MI:SS')
        , 300000, 100000,100,'MINU3','서울특별시 영등포구 문래동4가 수진빌딩',TO_DATE('2020-07-24 18:00:00','YYYY-MM-DD HH24:MI:SS')
        ,TO_DATE('2020-07-25 18:00:00','YYYY-MM-DD HH24:MI:SS'));

-- 거래 신고 처리 
INSERT INTO J_DEAL_REPORT(J_DEAL_REPORT_CODE, J_SUCCESS_CODE, G_DEAL_REPORT_TYPE_CODE,F_FILE, CONTENT, DEAL_REPORTER_TYPE_CODE)
VALUES('J_DRP'||SEQ_J_D_REP.NEXTVAL,'J_SUCCESS 1','GDERT3','FILE.pdf','접시가 완전 달라요 어이가 없네요.','DREPO4');


-- 게시물 신고하기 INSERT 
INSERT INTO J_POST_REPORT(J_POST_REPORT_CODE, J_POST_CODE, POST_REPORT_TYPE_CODE, B_USER_CODE)
VALUES('J_PRP'||SEQ_J_POST_REP_PRC.NEXTVAL,'J_POST3','POSRT6','USER11');


-- 더미 댓글
INSERT INTO J_REPLY(J_REPLY_CODE, J_POST_CODE, B_USER_CODE, L_LEVEL, REPLY)
VALUES('J_REP'||SEQ_J_REPLY.NEXTVAL,'J_POST2','USER11',0,'이거 접시 안깨지나요?' );

-- 댓글 신고 INSERT
INSERT INTO J_REPLY_REPORT(J_REPLY_REPORT_CODE, J_REPLY_CODE, REPLY_REPORT_TYPE_CODE, B_USER_CODE)
VALUES('J_REPR'||SEQ_J_REPLY_REP.NEXTVAL, 'J_REP1','REPRT1','USER12' );
